version: '3'
services: 
    app:
      build: .
      constainer_name: todo-app 
      environment: 
          -DATABASE_URL=postgresql://postgres:postgres@db:5432/todoapp
          -JWT_SECRET=your_jwt_secret_here
          -NODE_ENV=development
          -PORT=5003
      ports:
        - "5003:5003"
      depends_on:
        - db
      volumes:
        - .:/app 
    db:
      image: postgres:13-alpine
      constainer_name: postgres-db
      environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: afrivas2024
          POSTGRES_DB: todoapp
      ports:
        - "5432:5432"
      volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
